(cl:defpackage motoman_msgs-srv
  (:use )
  (:export
   "CMDJOINTTRAJECTORYEX"
   "<CMDJOINTTRAJECTORYEX-REQUEST>"
   "CMDJOINTTRAJECTORYEX-REQUEST"
   "<CMDJOINTTRAJECTORYEX-RESPONSE>"
   "CMDJOINTTRAJECTORYEX-RESPONSE"
  ))

