(cl:defpackage my_r2d2-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "MOVEROBOT"
   "<MOVEROBOT-REQUEST>"
   "MOVEROBOT-REQUEST"
   "<MOVEROBOT-RESPONSE>"
   "MOVEROBOT-RESPONSE"
  ))

