controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - left_joint_s
      - left_joint_l
      - left_joint_e
      - left_joint_u
      - left_joint_r
      - left_joint_b
      - left_joint_t
  - name: fake_second_manipulator_controller
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
  - name: fake_dual_manipulator_controller
    joints:
      - left_joint_s
      - left_joint_l
      - left_joint_e
      - left_joint_u
      - left_joint_r
      - left_joint_b
      - left_joint_t
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint